// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class madesomechangestovariabletypesindepartmenttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madesomechangestovariabletypesindepartmenttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201706010350553_made some changes to variable types in department table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
