// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MaderequiredProjectcolumnintasktables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaderequiredProjectcolumnintasktables));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051150167_Made required Project column in task tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
