// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Codefieldremovedfromprojectchartertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Codefieldremovedfromprojectchartertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201706101439126_Code field removed from project charter table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
