// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class AddedtablesforProjectCharterandStakeholders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedtablesforProjectCharterandStakeholders));
        
        string IMigrationMetadata.Id
        {
            get { return "201706090844108_Added tables for ProjectCharter and Stakeholders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
