// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateddatabasewithcorrectednullabletypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateddatabasewithcorrectednullabletypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201705171119091_updated database with corrected nullable types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
