// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Changedassignaskeytobool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedassignaskeytobool));
        
        string IMigrationMetadata.Id
        {
            get { return "201706220842136_Changed assign as key to bool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
