// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class uniquekeysaddedintables2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniquekeysaddedintables2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705220903317_unique keys added in tables 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
