// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addeddeletecascadesnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeddeletecascadesnew));
        
        string IMigrationMetadata.Id
        {
            get { return "201706030737202_Added delete cascades new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
