// <auto-generated />
namespace CitronSqlPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedtableforallowanceandjobhistorydetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtableforallowanceandjobhistorydetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201705170810056_added table for allowance and job history detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
